Document: qenes
Title: Debian qenes Manual
Author: <insert document author here>
Abstract: This manual describes what qenes is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/qenes/qenes.sgml.gz

Format: postscript
Files: /usr/share/doc/qenes/qenes.ps.gz

Format: text
Files: /usr/share/doc/qenes/qenes.text.gz

Format: HTML
Index: /usr/share/doc/qenes/html/index.html
Files: /usr/share/doc/qenes/html/*.html


